In [1]:
#conda install numpy
#pip install numpy
import numpy as np

### ТИПЫ ДАННЫХ
ЦЕЛОЧИСЛЕННЫЕ ТИПЫ ДАННЫХ В NUMPY

Это тип данных с общим корнем int. Int может быть со следующими окончаниями: int8, int16, int32 и int64. Окончание типа данных в NumPy показывает, сколько битов памяти должно быть выделено для хранения переменной.

In [3]:
import numpy as np
a = np.int8(25)
print(a)
print(type(a))

25
<class 'numpy.int8'>


In [15]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

В NumPy доступны и беззнаковые целочисленные типы данных. Они имеют корень uint (unsigned int — беззнаковое целое). uint доступны также с выделением памяти в 8, 16, 32 и 64 бита. При этом максимально возможное число оказывается в два раза больше, чем для соответствующего int, поскольку отрицательные числа исключены из типа данных uint.

In [25]:
b = np.uint8(-456)
print(b)
print(type(b))
np.iinfo(b)

56
<class 'numpy.uint8'>


iinfo(min=0, max=255, dtype=uint8)

In [13]:
np.iinfo(np.uint64)

iinfo(min=0, max=18446744073709551615, dtype=uint64)

НЕСКОЛЬКО ЗАМЕЧАНИЙ О ПРИВЕДЕНИИ ТИПОВ

In [16]:
# Тип данных не сохранится, если просто присвоить переменной с заданным NumPy-типом данных новое значение:
a = np.int32(1000)
print(a)
print(type(a))
a = 2056
print(a)
print(type(a))

1000
<class 'numpy.int32'>
2056
<class 'int'>


In [17]:
# Вместо этого следует снова указать нужный NumPy-тип данных:
a = np.int32(1000)
print(a)
print(type(a))
a = np.int32(2056)
print(a)
print(type(a))

1000
<class 'numpy.int32'>
2056
<class 'numpy.int32'>


In [18]:
# А вот арифметические операции сохраняют NumPy-тип данных:
a = np.int32(1000)
b = a + 25
print(b)
print(type(b))

1025
<class 'numpy.int32'>


In [19]:
# Следует понимать, что произойдёт, если выделенной памяти для хранения переменной окажется недостаточно.
a = np.int8(260)
print(a)

4


In [20]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
print(a + b)

2147483610 2147483605
-81


C:\Users\User\AppData\Local\Temp/ipykernel_1020/1517369409.py:4: RuntimeWarning: overflow encountered in long_scalars
  print(a + b)


ТИПЫ ДАННЫХ С ПЛАВАЮЩЕЙ ТОЧКОЙ В NUMPY

In [21]:
np.finfo(np.float16)

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [22]:
print(np.float16(4.12))
print(np.float16(4.13))
print(np.float16(4.123))
print(np.float16(4.124))
print(np.float16(4.125))

4.12
4.13
4.12
4.125
4.125


ДОПОЛНИТЕЛЬНЫЕ ТИПЫ ДАННЫХ В NUMPY

Следует обратить внимание на типы данных bool_ и str_. Они аналогичны bool и str из встроенных в Python, однако записывать их необходимо именно с нижним подчёркиванием, иначе произойдёт приведение к стандартному типу данных, а не типу NumPy. В целом, существенной разницы между этими типами данных нет, однако о такой двойственности следует помнить при сравнении типов переменных: тип bool не является эквивалентным numpy.bool_, несмотря на то что оба типа данных хранят значения True или False.

Примечание: в версиях NumPy 1.20 и выше появится предупреждение, если попытаться привести типы с помощью np.bool или np.str, а не np.bool_ или np.str_. Однако в более ранних версиях данное предупреждение не появляется.

Небольшое замечание про bool: несмотря на то что для хранения значения истина/ложь было бы достаточно только одного бита, из-за особенностей работы с памятью компьютера булевая переменная всё равно занимает в памяти целый байт.

In [23]:
a = True
print(type(a))
a = np.bool(a)
print(type(a))
a = np.bool_(a)
print(type(a))
 
# Значения равны
print(np.bool(True) == np.bool_(True))
print(type(np.bool(True)) == type(np.bool_(True)))

<class 'bool'>
<class 'bool'>
<class 'numpy.bool_'>
True
False


C:\Users\User\AppData\Local\Temp/ipykernel_1020/1297696083.py:3: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.bool(a)
C:\Users\User\AppData\Local\Temp/ipykernel_1020/1297696083.py:9: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(np.bool(True) == np.bool_(True))
C:\Users\User\AppData\Local\Temp/ipykernel_1020/1297696083.py:10: Deprecat

In [24]:
a = "Hello world!"
print(type(a))

a = np.str(a)
print(type(a))

a = np.str_(a)
print(type(a))

<class 'str'>
<class 'str'>
<class 'numpy.str_'>


C:\Users\User\AppData\Local\Temp/ipykernel_1020/346704570.py:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.str(a)


### Массивы
Однако массивы обладают особым свойством: элемент по любому номеру из массива можно получить за одно и то же время. Другими словами, неважно, находится элемент в начале, в середине или в конце списка — на времени получения элемента из массива по индексу (номеру) это никак не скажется.

Массив — это структура данных, в которой:
1. Элементы хранятся в указанном порядке.
2. Каждый элемент можно получить по индексу за одинаковое время.
3. Все элементы приведены к одному и тому же типу данных.
4. Максимальное число элементов и объём выделенной памяти заданы заранее.

Размерностью массива называют то число индексов, которое необходимо для однозначного получения элемента из массива.

Соответственно, чтобы найти элемент в массиве размерности 1 (строка из чисел) достаточно одного индекса.
В двумерном массиве (таблице из чисел) потребуется уже два индекса: номер строки и номер столбца.
Для трёхмерного массива (например, контейнеры на судне расположены по длине, ширине и высоте судна) потребуется уже три индекса.
Максимальная размерность массива программно не ограничена, но с добавлением каждой размерности в несколько раз увеличивается объём требуемой для его хранения памяти. Поэтому в какой-то момент места для массива большой размерности может не хватить, однако фактическая максимальная размерность зависит от возможностей компьютера.

Форма (структура) массива — это информация о количестве размерностей массива и протяжённости массива по каждой из размерностей. Например, можно задать двумерный массив размера 3x5 — у этой таблицы две размерности: 3 строки и 5 столбцов.

В списке не гарантируется получение любого элемента по индексу за одинаковое время (обычно чем больше индекс, тем дольше занимает время получения элемента).
Также с совокупностью элементов списка работать дольше, чем с элементами массива. На самом деле Python list является чем-то средним между классическим списком из теории структур данных и массивом, но по скорости он тоже проигрывает массивам.
Зато к преимуществам списка можно отнести легко изменяющуюся длину, а также возможность хранения данных разных типов в одной структуре данных. С другой стороны, последнее может быть и недостатком: при работе с массивами одинаковых данных можно быть уверенным, что там не окажется «сюрпризов» в виде данных неподходящего типа.

МАССИВЫ В NUMPY

In [26]:
import numpy as np
arr = np.array([1,5,2,9,10])
print(type(arr))

<class 'numpy.ndarray'>


In [27]:
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [28]:
arr = np.array([1,5,2,9,10])
arr.dtype

dtype('int32')

In [29]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [30]:
arr[2] = 2000
arr

array([  1,   5, -48,   9,  10], dtype=int8)

In [31]:
arr[2] = 125.5
arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [32]:
arr[2] = '12'
arr

array([ 1,  5, 12,  9, 10], dtype=int8)

СВОЙСТВА NUMPY-МАССИВОВ

In [37]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

In [34]:
# Узнать размерность массива можно с помощью .ndim:
arr.ndim
# 1
nd_arr.ndim
# 2

2

In [35]:
# Узнать общее число элементов в массиве можно с помощью .size:
arr.size
# 5
nd_arr.size
# 9

9

In [36]:
# Форма или структура массива хранится в атрибуте .shape:
arr.shape
# (5,)
nd_arr.shape
# (3, 3)

(3, 3)

In [38]:
# Наконец, узнать, сколько «весит» каждый элемент массива в байтах позволяет .itemsize:
arr.itemsize
# 1
nd_arr.itemsize
# 2

2

Массив из нулей создаётся функцией np.zeros. Она принимает аргументы shape (обязательный) — форма массива (одно число или кортеж) и dtype (необязательный) — тип данных, который будет храниться в массиве.

In [39]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

Ещё одной удобной функцией для создания одномерных массивов является arange. Она аналогична встроенной функции range, но обладает рядом особенностей. Вот её сигнатура: arange([start,] stop, [step,], dtype=None).

Аргументы start (по умолчанию 0), step (по умолчанию 1) и dtype (определяется автоматически) являются необязательными:

start (входит в диапазон возвращаемых значений) задаёт начальное число;
stop (не входит в диапазон возвращаемых значений, как и при использовании range) задаёт правую границу диапазона;
step задаёт шаг, с которым в массив добавляются новые значения.

In [40]:
np.arange(2.5, 5, 0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

На самом деле операции с плавающей точкой не всегда бывают предсказуемыми из-за особенностей хранения таких чисел в памяти компьютера. Поэтому для работы с дробными параметрами start, stop и step лучше использовать функцию linspace (англ. linear space — линейное пространство). Она тоже возвращает одномерный массив из чисел, расположенных на равном удалении друг от друга между началом и концом диапазона, но обладает немного другим поведением и сигнатурой:

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

start и stop являются обязательными параметрами, задающими начало и конец возвращаемого диапазона;
num — параметр, задающий число элементов, которое должно оказаться в массиве (по умолчанию 50);
endpoint — включён или исключён конец диапазона (по умолчанию включён);
retstep (по умолчанию False) позволяет указать, возвращать ли использованный шаг между значениями, помимо самого массива;
dtype — уже хорошо знакомый нам параметр, задающий тип данных (если не задан, определяется автоматически).

In [41]:
arr = np.linspace(1, 2, 10, endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [43]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(step)

0.45


ДЕЙСТВИЯ С МАССИВАМИ

In [45]:
import numpy as np
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [46]:
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [48]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [49]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

транспонирование. Эта операция меняет строки и столбцы массива местами. В NumPy эту операцию совершает функция transpose.

In [50]:
arr = np.arange(8)
arr.shape = (2, 4)
arr_trans = arr.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

ИНДЕКСЫ И СРЕЗЫ В МАССИВАХ

In [ ]:
# В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца:
elem_5_3 = mystery[4, 2]

# В переменную last сохраните элемент из последней строки последнего столбца
last = mystery[-1, -1]

# В переменную line_4 сохраните строку 4
line_4 = mystery[3]

# В переменную col_2 сохраните предпоследний столбец
col_2 = mystery[:, -2]

# Из строк 2-4 (включительно) получите столбцы 3-5 (включительно)
# Результат сохраните в переменную part
part = mystery[1:4, 2:5]

#  Сохраните в переменную rev последний столбец в обратном порядке
rev = mystery[::-1, -1]

# Сохраните в переменную trans транспонированный массив
trans = mystery.transpose()

СОРТИРОВКА ОДНОМЕРНЫХ МАССИВОВ

In [53]:
#Способ 1. Функция np.sort(<массив>) возвращает новый отсортированный массив:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
print(arr_new)

#Способ 2. Функция <массив>.sort() сортирует исходный массив и возвращает None:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
print(arr)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]
None
[ 3  4 12 12 15 23 23 45]


ВЕКТОРЫ В NUMPY И АРИФМЕТИКА

В программировании вектором называют одномерный проиндексированный набор данных, другими словами — одномерный массив.

Операция, применённая к двум векторам, на самом деле применяется поэлементно. То есть при сложении двух векторов первым элементом нового вектора будет сумма первых элементов исходных векторов, вторым — сумма вторых элементов и т. д.

Для совершения арифметических операций с векторами они должны быть одинаковой длины.

Исключением является случай, когда операция происходит с вектором и одним числом. Например, вектор целиком можно умножить на число или возвести в степень этого числа:

In [54]:
vec = np.arange(5)
vec * 10
# array([ 0, 10, 20, 30, 40])
vec ** 2
# array([ 0,  1,  4,  9, 16])

array([ 0,  1,  4,  9, 16], dtype=int32)

In [55]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
 
vec1 > vec2

array([False, False,  True, False])

In [56]:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26

array([ True,  True,  True,  True, False,  True, False])

В NumPy есть специальный подмодуль linalg, который позволяет производить операции из линейной алгебры.
Для вычисления длины вектора нам потребуется функция norm:

In [57]:
# Длина
length = np.linalg.norm(vec)
print(length)

109.23827168167757


In [58]:
# Расстояние
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance

12.206555615733702

In [59]:
# Скалярное произведение
scalar_product = np.dot(vec1, vec2)
scalar_product

47

БАЗОВЫЕ СТАТИСТИЧЕСКИЕ ФУНКЦИИ ДЛЯ ВЕКТОРОВ

Функции np.min и np.max позволяют находить максимальное и минимальное значение в векторе. Их можно записывать как в виде np.min(<vector>), так и в виде <vector>.min():
Функция mean позволяет посчитать среднее значение. Больше не требуется реализовывать её «руками»!

In [61]:
vec = np.array([2,7,18,28,18,1,8,4])
vec.min()

np.max(vec)

#vec.mean()

28

СЛУЧАЙНЫЕ ЧИСЛА В NUMPY

In [62]:
import numpy as np
np.random.rand()

0.46610633047879446

In [63]:
np.random.rand(2, 3)

array([[0.68365347, 0.3326279 , 0.02081743],
       [0.62710538, 0.79203022, 0.62655149]])

Возможно, именно функция sample покажется вам удобнее, поскольку информацию о форме массива обычно удобнее хранить в коде в виде кортежа и не задумываться потом о его распаковке. В остальном функция sample не отличается от rand.

In [67]:
np.random.uniform(-30, 50)

-13.731524607666188

In [68]:
np.random.uniform(-1000, 500, size=(2, 3))

array([[-417.51025578, -792.3051555 ,  -43.7390515 ],
       [-627.2605416 , -529.95294308,  286.20534607]])

 Для генерации целых чисел используется функция random.randint:

randint(low, high=None, size=None, dtype=int)

Функцию randint нельзя запустить совсем без параметров, необходимо указать хотя бы одно число.

Если указан только аргумент low, числа будут генерироваться от 0 до low-1, то есть верхняя граница не включается.

Если задать low и high, числа будут генерироваться от low (включительно) до high (не включительно).

size задаёт форму массива уже привычным для вас образом: одним числом — для одномерного или кортежем — для многомерного.

dtype позволяет задать конкретный тип данных, который должен быть использован в массиве.

In [69]:
np.random.randint(6, 12, size=(3,3))

array([[ 7, 10, 10],
       [ 7, 11,  7],
       [11,  9,  9]])

ГЕНЕРАЦИЯ ВЫБОРОК

In [71]:
arr = np.arange(6)
print(arr)
print(np.random.shuffle(arr))
arr

[0 1 2 3 4 5]
None


array([0, 2, 4, 3, 5, 1])

Функция random.shuffle перемешивает тот массив, к которому применяется, и возвращает None.

Обратите внимание, что необязательно передавать в функцию сразу массив: в этот раз мы передали в качестве аргумента список и ошибки не возникло. При этом на выходе получился уже NumPy-массив (это заметно по отсутствию запятых при печати массива). Сам список playlist при этом остался без изменений.

In [72]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
print(playlist)

['ACDC' 'The Beatles' 'Deep Purple' 'Pink Floyd']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


Чтобы получить случайный набор объектов из массива, используется функция random.choice:

choice(a, size=None, replace=True)

a — массив или число для генерации arange(a);

size — желаемая форма массива (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);

replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).

Выборка с повторениями используется по умолчанию. Она применяется в том случае, когда мы допускаем, что объекты могут повторяться.

In [73]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['Maria' 'Kate']


In [74]:
choice = np.random.choice([1,2,3,4,5,6], size=10)
print(choice)

[4 5 5 4 1 5 3 1 1 4]


SEED ГЕНЕРАТОРА ПСЕВДОСЛУЧАЙНЫХ ЧИСЕЛ

 Как уже было сказано ранее, NumPy генерирует не истинные случайные числа (такие числа получаются в результате случайных процессов), а псевдослучайные, которые получаются с помощью особых преобразований какого-либо исходного числа. Обычно компьютер берёт это число автоматически, например, из текущего времени в микросекундах (на самом деле используются другие ещё менее предсказуемые числа). Такое число называют seed (от англ. — «зерно»).

 Самостоятельно задать seed в NumPy можно с помощью функции np.random.seed(<np.uint32>). Число в скобках должно быть в пределах от 0 до 2**32 - 1 (=4294967295).

In [75]:
np.random.seed(23)
np.random.randint(10, size=(3,4))

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])